### ISSUE TITLE
Error with ObjectBuffer Class.

### ISSUE THREAD

**Issue by WarrenXiaGG** [OpenGGEngine/OpenGG-Project#27]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 11529, Size: 11529
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.opengg.core.buffer.ObjectBuffers.genBuffer(ObjectBuffers.java:31)
    at com.opengg.test.OpenGGTest.setup(OpenGGTest.java:157)
    at com.opengg.test.OpenGGTest.<init>(OpenGGTest.java:117)
    at com.opengg.test.OpenGGTest.main(OpenGGTest.java:73)
Java Result: 1

**Comment by WarrenXiaGG** [comment]
This only occurs on certain obj files like awp.obj
